import Head from "next/head";
import Sample from "components/Sample";
import client from "api/client";
import { useQuery } from "react-query";
import { useRouter } from "next/router";
import AppLayout from "components/AppLayout";

const getPosts = (config) => client.get("/todos", config);

// getServerSideProps
export async function getServerSideProps() {
  const posts = await getPosts({
    headers: {
      authorization: "Bearer servertest",
    },
  });
  return { props: { posts, isGood: true } };
}

export default function Home({ posts, isGood }) {
  const { data } = useQuery("posts", getPosts, {
    initialData: posts,
    placeholderData: [],
  });
  const router = useRouter();

  return (
    <AppLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-3xl">Sample</div>
      <button
        className="py-3"
        type="button"
        onClick={() => router.push("/about", undefined, { shallow: true })}
      >
        To about link
      </button>
      {isGood && "True"}
      {data.map((item) => (
        <div key={item.id}>{item.title}</div>
      ))}
      <Sample />
    </AppLayout>
  );
}
